name: Build/Test

on:
 push:

env:
  CLIENT_CONFIG: ./config/client.properties

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Prepare
        run: |
          sed -i 's+{{ TODO_SERVER }}+${{ vars.CONFLUENT_SERVER }}+g' ${{ env.CLIENT_CONFIG }}
          sed -i 's+{{ TODO_KEY }}+${{ secrets.CONFLUENT_API_KEY }}+g' ${{ env.CLIENT_CONFIG }}
          sed -i 's+{{ TODO_SECRET }}+${{ secrets.CONFLUENT_API_KEY_SECRET }}+g' ${{ env.CLIENT_CONFIG }}
          sed -i 's+{{ TODO_REGISTRY_SERVER }}+${{ vars.CONFLUENT_SERVER }}+g' ${{ env.CLIENT_CONFIG }}
          sed -i 's+{{ TODO_REGISTRY_KEY }}+${{ secrets.CONFLUENT_API_KEY }}+g' ${{ env.CLIENT_CONFIG }}
          sed -i 's+{{ TODO_REGISTRY_SECRET }}+${{ secrets.CONFLUENT_API_KEY_SECRET }}+g' ${{ env.CLIENT_CONFIG }}
          cat ${{ env.CLIENT_CONFIG }}

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test -i