name: Build/Test

on:
 push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradlew
        run: ./gradlew

      - name: Prepare
        run: |
          sed -i 's/{{ TODO_SERVER }}/${ vars.CONFLUENT_SERVER }/g' ./config/client.properties
          sed -i 's/{{ TODO_KEY }}/${ vars.CONFLUENT_API_KEY }/g' ./config/client.properties
          sed -i 's/{{ TODO_SECRET }}/${ vars.CONFLUENT_API_KEY_SECRET }/g' ./config/client.properties
          sed -i 's/{{ TODO_REGISTRY_SERVER }}/${ vars.CONFLUENT_SERVER }/g' ./config/client.properties
          sed -i 's/{{ TODO_REGISTRY_KEY }}/${ vars.CONFLUENT_API_KEY }/g' ./config/client.properties
          sed -i 's/{{ TODO_REGISTRY_SECRET }}/${ vars.CONFLUENT_API_KEY_SECRET }/g' ./config/client.properties
          cat ./config/client.properties

      - name: Build
        run: ./gradlew shadowJar

      - name: Test
        run: ./gradlew test -i